# this would be in your github actions folder
on:
  push:
    branches:
      - main


jobs:
  test_notebooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter
        pip install -r requirements.txt

    - name: Run notebook tests
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }} # env vars referenced in notebook
      run: |
        jupyter nbconvert --execute --to notebook example_notebook.ipynb